# QoL
set -g base-index 1
set -g pane-base-index 1
set -g mouse on
set -g status-position top

# Copy mode uses vi keys
setw -g mode-keys vi

# CWD on new windows and splits
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Catppuccin options (must be set before plugins run)
set -g @catppuccin_window_text         " #W"
set -g @catppuccin_window_current_text " #W"
set -g automatic-rename on
set -g automatic-rename-format "#{pane_current_command}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
